def build(bld):
	# 1. A simple program
#  	obj = bld.createObj('cpp', 'program')
#  	obj.source='''
#  	main.cpp
#  	'''
#  	obj.includes='.'
#  	obj.useliblocal='./orocos-kinematics.a'
#  	obj.uselib='OROCOS'
#  	obj.target='kine-test'

	# 2. A shared library
	# The extension (.so) is added automatically
# 	obj = bld.createObj('cpp', 'shlib')
# 	obj.source='''
# 	KinematicsComponent.cxx
# 	'''
# 	obj.includes='.'
# 	obj.uselib='OROCOS'
# 	obj.target='orocos-kinematics'

	# 3. A static library
	# The extension (.a) is added automatically
	obj = bld.createObj('cpp', 'staticlib')
	obj.source='''
	KinematicsComponent.cxx
	'''
	obj.uselib='OROCOS'
	obj.includes='.'
	obj.target='orocos-kinematics'

def set_options(opt):
	# options defined if src/ was to be compiled as a standalone module
	print 'ok'


def configure(conf):
	print 'ok'
