#
# Change the CPPFLAGS and compile with:
#      make -C /usr/src/linux-2.6.9_hal-r10/ SUBDIRS=$PWD modules
#
CPPFLAGS+=-I/usr/include -I/usr/realtime/rtai-magma_linux-2.6.9_hal-r10/include
obj-m := VIPC616board.o IP-Encoder-6.o IP-FastDAC.o IP-Digital_24.o IP-OptoInput.o JR3DSP.o LiAS_lxrt_kernel.o
