# FIXME: Remove these absolute paths
#CPPFLAGS+=-I/usr/realtime/rtai3.2_linux-2.6.9_adeos-r9c3/include
CPPFLAGS+=" -I/home/sspr/src/orocos-trunk/build/packages/install/include "
CPPFLAGS+=" -I/usr/src/linux "
obj-m := cplinux.o cpuser.o cpfifo.o cpmsg.c cpfilter.o

VERBOSE=1

# type "make -C /usr/src/linux/ SUBDIRS=$PWD modules"