Document: orocos-ocl
Title: Debian orocos-ocl Manual
Author: <insert document author here>
Abstract: This manual describes what orocos-ocl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/orocos-ocl/orocos-ocl.sgml.gz

Format: postscript
Files: /usr/share/doc/orocos-ocl/orocos-ocl.ps.gz

Format: text
Files: /usr/share/doc/orocos-ocl/orocos-ocl.text.gz

Format: HTML
Index: /usr/share/doc/orocos-ocl/html/index.html
Files: /usr/share/doc/orocos-ocl/html/*.html

  
