
# This basically copies a file to the build directory.
MACRO( TEST_USES_FILE FILE )
  message("COMMAND copy ${CMAKE_CURRENT_SOURCE_DIR}/${FILE} -> ${CMAKE_CURRENT_BINARY_DIR}/${FILE}")
  CONFIGURE_FILE(
	"${CMAKE_CURRENT_SOURCE_DIR}/${FILE}"
	"${CMAKE_CURRENT_BINARY_DIR}/${FILE}"  COPYONLY)
ENDMACRO( TEST_USES_FILE FILE )
